// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApaX_JrYqhZtrkFpNP6xV2j3MzyqBPx8',
    appId: '1:376358532668:web:a9732335f510a8b22df539',
    messagingSenderId: '376358532668',
    projectId: 'nssapp-c98cf',
    authDomain: 'nssapp-c98cf.firebaseapp.com',
    storageBucket: 'nssapp-c98cf.appspot.com',
    measurementId: 'G-DK55HHEKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwWt71xJIpSqawbc5p6l_9U0I6I1yDs8s',
    appId: '1:376358532668:android:e7499d82357b32a52df539',
    messagingSenderId: '376358532668',
    projectId: 'nssapp-c98cf',
    storageBucket: 'nssapp-c98cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIbaKtqW_Q8pFRGUUS2-NIugsjUCjaao',
    appId: '1:376358532668:ios:b0b30014c1fe8bb72df539',
    messagingSenderId: '376358532668',
    projectId: 'nssapp-c98cf',
    storageBucket: 'nssapp-c98cf.appspot.com',
    iosClientId: '376358532668-mp84ipquvqvetiq4d694vp2g6r567osn.apps.googleusercontent.com',
    iosBundleId: 'edu.somaiya.nssapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsIbaKtqW_Q8pFRGUUS2-NIugsjUCjaao',
    appId: '1:376358532668:ios:b0b30014c1fe8bb72df539',
    messagingSenderId: '376358532668',
    projectId: 'nssapp-c98cf',
    storageBucket: 'nssapp-c98cf.appspot.com',
    iosClientId: '376358532668-mp84ipquvqvetiq4d694vp2g6r567osn.apps.googleusercontent.com',
    iosBundleId: 'edu.somaiya.nssapp',
  );
}
